package com.sample.rules;

import java.util.List;
import java.util.ArrayList;
import org.kie.api.runtime.KieRuntime;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

import com.sample.QuestionDialog;


global JFrame frame;
global javax.swing.JTextArea textArea;

// Definicja klasy GUIState
declare GUIState
    trescPytania: String
    opcje_odpowiedzi: List
    odpowiedz: String
end


rule "Init"
    when
    then
        String question = "What type of game are you looking for? Do you want to hone the ultimate warrior, or build a mighty nation?";
        List<String> answers = new ArrayList<>();
        answers.add("SHOOTERS");
        answers.add("RPGS");
        answers.add("STRATEGY");
        answers.add("VIRTUAL WORLDS");
        String final_answer = null;
        insert(new GUIState(question, answers, final_answer));
end

rule "Game Type"
    when
        t: GUIState(trescPytania == "What type of game are you looking for? Do you want to hone the ultimate warrior, or build a mighty nation?" && odpowiedz == null);
    then
        System.out.println("EUREKA");
        QuestionDialog dialog = new QuestionDialog(t.getTrescPytania(), t.getOpcje_odpowiedzi());
        String selectedAnswer = dialog.showAndWait();
        t.setOdpowiedz(selectedAnswer);
        System.out.println("Selected answer: " + selectedAnswer);
        update(t);  
end

rule "Shooter"
	when
		t: GUIState(odpowiedz == "SHOOTERS");
	then
		String question = "Would you rather fight on the ground or while flying through space?";
        List<String> answers = new ArrayList<>();
        answers.add("Flying  through space");
        answers.add("On the ground");
        String final_answer = null;
        insert(new GUIState(question, answers, final_answer));
end;


rule "Fight place"
    when
        t: GUIState(trescPytania == "Would you rather fight on the ground or while flying through space?" && odpowiedz == null);
    then
        QuestionDialog dialog = new QuestionDialog(t.getTrescPytania(), t.getOpcje_odpowiedzi());
        String selectedAnswer = dialog.showAndWait();
        t.setOdpowiedz(selectedAnswer);
        System.out.println("Selected answer: " + selectedAnswer);
        update(t);  
end


